# Generated by Django 6.0.7 on 2026-07-15 19:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_in_words', models.TextField(blank=True, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], db_index=True, default='pending', max_length=20)),
                ('match_status', models.CharField(choices=[('match', 'Match'), ('mismatch', 'Mismatch'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cheques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_no'], name='cheques_trackin_faae87_idx'), models.Index(fields=['status'], name='cheques_status_71171b_idx'), models.Index(fields=['created_at'], name='cheques_created_a872f9_idx'), models.Index(fields=['match_status'], name='cheques_match_s_e37a95_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='audit_log_table_n_38ccfb_idx'), models.Index(fields=['performed_by', '-created_at'], name='audit_log_perform_50aa7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChequeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('front_uv', 'Front UV'), ('back_uv', 'Back UV')], max_length=20)),
                ('file_path', models.TextField()),
                ('file_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.cheque')),
            ],
            options={
                'db_table': 'cheque_images',
                'indexes': [models.Index(fields=['cheque', 'image_type'], name='cheque_imag_cheque__368322_idx')],
                'unique_together': {('cheque', 'image_type')},
            },
        ),
        migrations.CreateModel(
            name='OCRData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('amount', 'Amount'), ('date', 'Date'), ('beneficiary_name', 'Beneficiary Name'), ('account_number', 'Account Number'), ('cheque_number', 'Cheque Number'), ('bank_code', 'Bank Code'), ('branch_code', 'Branch Code'), ('amount_in_words', 'Amount In Words')], max_length=100)),
                ('field_value', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_data', to='dashboard.cheque')),
            ],
            options={
                'db_table': 'ocr_data',
                'ordering': ['field_name'],
                'indexes': [models.Index(fields=['cheque', 'field_name'], name='ocr_data_cheque__bd12f5_idx')],
                'unique_together': {('cheque', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='ProcessingQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('queue_status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queues', to=settings.AUTH_USER_MODEL)),
                ('cheque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='dashboard.cheque')),
            ],
            options={
                'db_table': 'processing_queue',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['queue_status', 'priority'], name='processing__queue_s_4b65bc_idx'), models.Index(fields=['assigned_to'], name='processing__assigne_1d2026_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='dashboard.cheque')),
            ],
            options={
                'db_table': 'status_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['cheque', '-changed_at'], name='status_hist_cheque__f054ad_idx')],
            },
        ),
    ]
