# Generated by Django 6.0.7 on 2026-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='match_status',
            field=models.CharField(choices=[('match', 'Match'), ('mismatch', 'Mismatch')], db_index=True, default='mismatch', max_length=20),
        ),
    ]
